export const CATEGORIES = {
  Destinations: [
    "Cebu Highlights",
    "Beaches and Islands",
    "Mountain Escapes",
    "Heritage and History",
    "Hidden Gems",
    "Travel Itineraries",
  ],
  "Brands and Products": [
    "Homegrown Brands",
    "Fashion and Apparel",
    "Tech and Gadgets",
    "Beauty and Wellness",
    "Food Products",
    "Eco-Friendly and Sustainable",
  ],
  Stories: [
    "Life in Cebu",
    "Resilience and Recovery",
    "Student Stories",
    "Entrepreneur Journeys",
    "Cultural Narratives",
    "Inspirational Profiles",
  ],
  "News and Entertainment": [
    "Breaking News Cebu",
    "Local Governance",
    "Festivals and Events",
    "Entertainment Buzz",
    "Music and Arts",
    "Sports",
    "Campus News",
  ],
  Food: [
    "Cebu Favorites",
    "Street Food Finds",
    "Café and Coffee Spots",
    "Seafood Specials",
    "Sweet Treats and Desserts",
    "Food Reviews",
  ],
};
